services:
  postgres:
    image: postgres:15
    container_name: pgdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hari1818
      POSTGRES_DB: studentDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./StudentBackend
    container_name: springapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/studentDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Hari1818
    depends_on:
      - postgres

  frontend:
    build: ./StudentFrontend
    container_name: frontendapp
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
