version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: pgdb
    environment:
      POSTGRES_USER: hari
      POSTGRES_PASSWORD: hari123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./StudentBackend
    container_name: springapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: hari
      SPRING_DATASOURCE_PASSWORD: hari123
    depends_on:
      - postgres

  frontend:
    build: ./StudentFrontend
    container_name: frontendapp
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
